### ISSUE TITLE
Publish a version to PyPI

### ISSUE THREAD

**Issue by ncoghlan** [fedora-modularity/depchase#14]
While libsolv isn't yet pip installable (see https://github.com/ncoghlan/pypi-solv/issues/1 ), depchase can still usefully be installed into virtual environments that have access to system site packages (and hence the libsolv Python bindings).

So it would be handy to have a version of depchase up on PyPI (and the name seems to be free).

I'd also be happy to do it if you'd prefer that (I can grant shared publisher access afterwards)

**Comment by ignatenkobrain** [comment]
No, neither libsolv not depchase will be on PyPI.

I don't see any value in this. Moreover, this is just internal tool which ideally should die as soon as possible. Once copr, Koji, MBS or whatever else will gain proper functionality.

**Comment by ncoghlan** [comment]
The proper functionality is what I'm looking to add to the rpm2module command in https://pagure.io/modularity/modularity-tools/, but I don't want to tightly couple it to the Fedora build pipeline - as with `depchase`, I want to switch it to instead rely on the package and module metadata consumed by DNF, so it will work with arbitrary module-aware repos, not just the Fedora ones.

Now, I *can* do that just by copying the code and concepts I need out of `depchase`, but that only makes sense if `depchase` is going to be deprecated entirely - otherwise we're going to end up maintaining two slightly different code bases that do essentially the same thing.

**Comment by ignatenkobrain** [comment]
There is just no point in this. Depchase is just binary without any guarantee that output will not change format.. As I was always saying, rpm2module either should become part of depchase or should not rely on depchase..

Langdon or Adam probably should remember some more details since we had meeting about that..

Also there is huge question if rpm2module should exist in first place. The functionality should be in MBS or service like that.

**Comment by ncoghlan** [comment]
Why would we couple this tightly to the Fedora build infrastructure when there's no reason to do so? That would be like saying "pyp2rpm shouldn't exist, the functionality should be in Koji instead".

Now, offering things like pyp2rpm *as* a web service after they already exist (as with COPR's "Build from PyPI" feature) can definitely make sense, but that doesn't necessarily mean it's the right way to build them in the first place.

**Comment by TomasTomecek** [comment]
> I don't see any value in this.

I do. I wanna create a module for Y. I'll run one command and have boilerplate modulemd ready.

> Moreover, this is just internal tool...

It's not. It's packaged in Fedora.

> ...which ideally should die as soon as possible.

Why?

> Once copr, Koji, MBS or whatever else will gain proper functionality.

Will they? Is it on some roadmap?

> Also there is huge question if rpm2module should exist in first place. The functionality should be in MBS or service like that.

Why? I prefer having a separate, standalone, command-line tool, instead of relaying on a service and overload functionality of the service.

**Comment by ignatenkobrain** [comment]
@TomasTomecek @ncoghlan 

> I do. I wanna create a module for Y. I'll run one command and have boilerplate modulemd ready.

You simply can not. Let me describe reasoning why depchase is a internal / temporary tools..

The problem is that you can't generate modulemd out of some repodata, it is simply not enough. There migh be circular dependencies, bootstrapping stuff and it's just impossible to find buildorder until you start building stuff. So it should be part of buildsystem. Even different buildroot can affect buildorder.

> It's not. It's packaged in Fedora.

```
$ sudo dnf install depchase
Last metadata expiration check: 0:58:32 ago on Tue 26 Sep 2017 11:39:30 AM CEST.
No package depchase available.
Error: Unable to find a match
```

> Will they? Is it on some roadmap?

Ask maintainers of those tools, I think @asamalik might have better clue about state of things..

> Why? I prefer having a separate, standalone, command-line tool, instead of relaying on a service and overload functionality of the service.

There is no point in this, because you need basically full buildsystem to figure out order and stuff like that. depchase will basically stop working as soon as we will get rid out of non-modular fedora.

**Comment by asamalik** [comment]
I support @ncoghlan 's proposal. Depchase is a very helpful tool it would be a pity not to make it even more accessible.

@ignatenkobrain From what I have read here, @ncoghlan is not asking you to do any work. He is even proposing that he will do all the work. Be proud your work is being useful to others!

**Comment by ignatenkobrain** [comment]
@ncoghlan so do you have some summary how and what for you want to use depchase? Could you dump it here or send me a mail?

the main reason I don't want to see depchase on pypi that people would rely on its CLI which is definitely not what I want. I have absolutely nothing against having any new functionality in depchase, but I'm very afraid that people will rely on depchase in their scripts and that's the reason I don't want it on PyPI...

On a side note, I was thinking to rewrite depchase in Rust or C because python bindings often do not expose all necessary APIs in many cases.

**Comment by TomasTomecek** [comment]
Oh, now I get the confusion, I was talking about fedmod/mod-tools, while you, @ignatenkobrain, was talking about depchase. Therefore my arguments are invalid. I agree with you that we need "something" to help us battle dependencies.

**Comment by ignatenkobrain** [comment]
@TomasTomecek well, I was talking about both ;)

**Comment by ignatenkobrain** [comment]
@TomasTomecek feel free to check out https://pagure.io/fm-orchestrator/issue/715 as well ;)

**Comment by ncoghlan** [comment]
While I slightly misunderstood @ignatenkobrain's concern (I assumed it was Python API stability he wanted to avoid committing to moreso than CLI stability), I was close enough that I still think the approach I proposed in https://pagure.io/modularity/modularity-tools/issue/52#comment-468444 is the right way to go: modularity-tools/fedmod will become the home of the stable CLI and Python API, while depchase will remain a purely internal tool, with no stability guarantees.

I'll still use the depchase code as a starting point, I'll just bring it in by copying it, rather than by using it as a dependency.

I then expect that over time either fedmod will take over all of depchase's current use cases, or else depchase will gain a dependency on fedmod's Python API.

Regarding the complexity of solving the *whole* modulemd generation problem, I'm not actually interested in doing that - similar to tools like pyp2rpm, I only want to tackle the proverbial 80% of cases that are relatively easy to handle automatically, which will then mean that human intervention should only be needed in the cases where the naive automation fails.

My rationale for that is that in the future, we're going to be encouraging people to write module definitions *instead of* metapackages and yum groups, so ongoing maintenance should be inverted, with metapackages & yum groups being generated from the more-appropriate-to-the-task modulemd files, rather than the other way around.

**Comment by TomasTomecek** [comment]
> modularity-tools/fedmod will become the home of the stable CLI and Python API

+1
